### ISSUE TITLE
IncrementalInference creates name, shouldn't be passed in as part of request - will come back in response.

### ISSUE THREAD

**Issue by GearsAD** [MarineRoboticsGroup/graff_cpp#8]
https://github.com/pvazteixeira/graff_cpp/blob/8cb657a15dc83a7f3a61683612bd4ae4b3c08e8c/include/graff/graff.hpp#L183

**Comment by pvazteixeira** [comment]
Fixed:
https://github.com/MarineRoboticsGroup/graff_cpp/blob/807d4bda950c4e543de1070ed8864166eeeb12db/include/graff/graff.hpp#L262
